services:
  api:
    image: quadraja
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - quadraja-network

  db:
    image: postgres:15.10
    container_name: postgres
    environment:
      POSTGRES_USER: montonurb
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quadraja
    ports:
      - "5432:5432"
    networks:
      - quadraja-network

networks:
  quadraja-network:
    driver: bridge
