services:
  api:
    image: quadraja
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quadra-ja
    ports:
      - "5432:5432"